<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>89ca90b2-c5e7-4f39-920d-2c22901fbcbf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new offer where 
        the discount is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
