<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Standard offer</name>
  <uuid>2ea4090d-b334-42b2-9aba-6a03d0af955a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Sum* (1-the discount of 'loyalty promotion') ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
