<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>bb788596-d845-4a6b-82e4-c24f65f25929</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined
then
	set decision to "Hello " + Name + "!" + 'Weather advice';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
