<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>sum</name>
  <uuid>5511bef9-ecd1-4144-b6b1-8dc4c7be2857</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each product in Products : 
	- set decision to decision + the price of this product; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
